cron_last_epoch_time_this_line_was_supposedly_executed:
	gcc -DCRON_USE_LOCAL_TIME -o cron_last_epoch_time_this_line_was_supposedly_executed cron_last_epoch_time_this_line_was_supposedly_executed.c ccronexpr.c
